services:
  kobuki:
    build:
      dockerfile: Dockerfile
    command: ros2 launch kobuki kobuki_joystick.launch.py
    restart: always
    privileged: true
    network_mode: host
    volumes:
      - /dev/kobuki:/dev/kobuki
